const ON_USERS_LOADED = 'ON_USERS_LOADED';
const ON_ADD_TO_BAD = 'ON_ADD_TO_BAD';
const ON_REMOVE_FROM_BAD = 'ON_REMOVE_FROM_BAD';

export {
    ON_USERS_LOADED,
    ON_ADD_TO_BAD,
    ON_REMOVE_FROM_BAD,
}
